// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolarDrinks.Data;

#nullable disable

namespace PolarDrinks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906023314_AdicionarLojaOnline")]
    partial class AdicionarLojaOnline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolarDrinks.Models.CompraEstoqueModel", b =>
                {
                    b.Property<int>("CompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraID"));

                    b.Property<DateTime>("CompraData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompraDataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompraStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FornecedorID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CompraID");

                    b.HasIndex("FornecedorID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("ComprasEstoque");
                });

            modelBuilder.Entity("PolarDrinks.Models.FornecedorModel", b =>
                {
                    b.Property<int>("FornecedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FornecedorID"));

                    b.Property<bool>("FornecedorAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("FornecedorBairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FornecedorCEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FornecedorCNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("FornecedorCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FornecedorEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FornecedorEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FornecedorLogradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FornecedorNome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FornecedorNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FornecedorTelefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("FornecedorID");

                    b.HasIndex("FornecedorCNPJ")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("PolarDrinks.Models.ItemCompraModel", b =>
                {
                    b.Property<int>("ItemCompraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCompraID"));

                    b.Property<int>("CompraID")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCompraPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemCompraQtd")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("ItemCompraID");

                    b.HasIndex("CompraID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ItensCompra");
                });

            modelBuilder.Entity("PolarDrinks.Models.ItemVendaModel", b =>
                {
                    b.Property<int>("ItemVendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemVendaID"));

                    b.Property<decimal>("ItemVendaCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItemVendaPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemVendaQtd")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("VendaID");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.CarrinhoItemModel", b =>
                {
                    b.Property<int>("CarrinhoItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrinhoItemID"));

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("CarrinhoItemID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("CategoriaAtiva")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.ClienteModel", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<bool>("ClienteAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("ClienteCPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("ClienteCriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClienteSenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteID");

                    b.HasIndex("ClienteCPF")
                        .IsUnique();

                    b.HasIndex("ClienteEmail")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.ItemPedidoModel", b =>
                {
                    b.Property<int>("ItemPedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemPedidoID"));

                    b.Property<decimal>("ItemPedidoCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItemPedidoPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemPedidoQtd")
                        .HasColumnType("int");

                    b.Property<int>("PedidoID")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("ItemPedidoID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.PedidoModel", b =>
                {
                    b.Property<int>("PedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("PedidoCodigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("PedidoData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PedidoDataConcluido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PedidoDataSeparado")
                        .HasColumnType("datetime2");

                    b.Property<string>("PedidoStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PedidoValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioEntregouID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioSeparouID")
                        .HasColumnType("int");

                    b.HasKey("PedidoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("UsuarioEntregouID");

                    b.HasIndex("UsuarioSeparouID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.ProdutoCategoriaModel", b =>
                {
                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.HasKey("ProdutoID", "CategoriaID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("ProdutoCategorias");
                });

            modelBuilder.Entity("PolarDrinks.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.Property<int>("MovimentacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimentacaoID"));

                    b.Property<int?>("ItemCompraID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemPedidoID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemVendaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovimentacaoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovimentacaoDescricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MovimentacaoQtd")
                        .HasColumnType("int");

                    b.Property<string>("MovimentacaoTipo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("MovimentacaoID");

                    b.HasIndex("ItemCompraID");

                    b.HasIndex("ItemPedidoID");

                    b.HasIndex("ItemVendaID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("PolarDrinks.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoID"));

                    b.Property<bool>("ProdutoAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("ProdutoCodBarra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProdutoDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProdutoEstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProdutoPrecoCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProdutoPrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProdutoPromocao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProdutoQtdEstoque")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProdutoID");

                    b.HasIndex("ProdutoCodBarra")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PolarDrinks.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("UsuarioAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UsuarioCriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PolarDrinks.Models.VendaModel", b =>
                {
                    b.Property<int>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaID"));

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("VendaCancelada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VendaData")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendaTipoPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("VendaValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("PolarDrinks.Models.CompraEstoqueModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.FornecedorModel", "Fornecedor")
                        .WithMany("Compras")
                        .HasForeignKey("FornecedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fornecedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PolarDrinks.Models.ItemCompraModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.CompraEstoqueModel", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CompraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PolarDrinks.Models.ItemVendaModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.VendaModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.CarrinhoItemModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.Loja.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.ItemPedidoModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.Loja.PedidoModel", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.PedidoModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.Loja.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.UsuarioModel", "UsuarioEntregou")
                        .WithMany()
                        .HasForeignKey("UsuarioEntregouID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolarDrinks.Models.UsuarioModel", "UsuarioSeparou")
                        .WithMany()
                        .HasForeignKey("UsuarioSeparouID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioEntregou");

                    b.Navigation("UsuarioSeparou");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.ProdutoCategoriaModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.Loja.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PolarDrinks.Models.MovimentacaoEstoqueModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.ItemCompraModel", "ItemCompra")
                        .WithMany()
                        .HasForeignKey("ItemCompraID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolarDrinks.Models.Loja.ItemPedidoModel", "ItemPedido")
                        .WithMany()
                        .HasForeignKey("ItemPedidoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolarDrinks.Models.ItemVendaModel", "ItemVenda")
                        .WithMany()
                        .HasForeignKey("ItemVendaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolarDrinks.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolarDrinks.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ItemCompra");

                    b.Navigation("ItemPedido");

                    b.Navigation("ItemVenda");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PolarDrinks.Models.VendaModel", b =>
                {
                    b.HasOne("PolarDrinks.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PolarDrinks.Models.CompraEstoqueModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PolarDrinks.Models.FornecedorModel", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("PolarDrinks.Models.Loja.PedidoModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PolarDrinks.Models.VendaModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
